DELIVERY_TYPE = 'neoship'

SHIPPER_CODE_PACKETA = 'packeta'
SHIPPER_CODES_WITH_CARRIER_TYPE = (SHIPPER_CODE_PACKETA,)

OPTION_KIND_SHIPPER = 'shipper'
OPTION_KIND_CARRIER_TYPE = 'carrier_type'

ODOO_DELIVERY_TYPE_FIXED = 'fixed'
ODOO_PRODUCT_TYPE_SERVICE = 'service'
ODOO_INVOICE_POLICY_ORDER = 'order'
